// export const sellers = [
//   {
//     "Business #": 1,
//     "Business Model": "Manufacturing eco-friendly packaging solutions.",
//     "The Clients": "Large food and beverage companies.",
//     "Value Proposition":
//       "Our packaging is 100% recyclable and reduces costs for clients.",
//     "Product/Service Offerings": 25,
//     "Revenue Streams": "Product sales, consultancy services.",
//     "Marketing Channels": "Online, trade shows, direct sales.",
//     "Geographic Location": "Amsterdam",
//     Revenue: 5000000,
//     "Profit Margins": "20%",
//     "Economic Indicators": "Positive, driven by eco-friendly trends.",
//     "Regulatory Environment": "Favorable for eco-friendly products.",
//     "Media Coverage": "Positive media coverage.",
//     "Strategic Vision": "Expanding into new markets.",
//     "Innovation and Technology Adoption":
//       "Investing in new eco-friendly technologies.",
//     "Market Expansion Capability": "High, with a focus on Europe.",
//     "Partnerships and Alliances": "Partnering with major food companies.",
//     "Leadership Style": "Visionary and innovative.",
//     "Company Culture": "Sustainability-focused.",
//     "Management Style": "Agile and adaptive.",
//     "Employee Satisfaction": "High (90%)",
//     "Customer Satisfaction": "High (85%)",
//     "Stakeholder Relationships": "Strong relationships with stakeholders.",
//     "Ethical Standards": "High ethical standards.",
//     Values: "Core values: sustainability, innovation.",
//     "Diversity & Inclusion": "Promotes diversity and inclusion.",
//     "Transition Plan Compatibility":
//       "Seamless transition with comprehensive plan.",
//     "Owner Involvement": "Owner to remain involved for 1 year.",
//     "Cultural Integration Readiness": "High readiness for integration.",
//     "Seller Story": "Founded to address the need for sustainable packaging.",
//     "Communication Style": "Clear and transparent.",
//     "Decision-Making Process": "Collaborative decision-making.",
//     "Conflict Resolution": "Proactive and solution-oriented.",
//     "Communication Frequency": "Regular updates and meetings.",
//   },
//   {
//     "Business #": 2,
//     "Business Model": "Manufacturing bespoke furniture.",
//     "The Clients": "High-end furniture retailers and interior designers.",
//     "Value Proposition":
//       "High-quality, customizable furniture to fit any space.",
//     "Product/Service Offerings": 30,
//     "Revenue Streams": "Product sales, design services.",
//     "Marketing Channels": "Trade shows, online marketing, direct sales.",
//     "Geographic Location": "Utrecht",
//     Revenue: 3000000,
//     "Profit Margins": "25%",
//     "Economic Indicators": "Stable, driven by demand for bespoke furniture.",
//     "Regulatory Environment": "Supportive for high-end furniture.",
//     "Media Coverage": "Positive media coverage in design magazines.",
//     "Strategic Vision": "Expanding product lines and market reach.",
//     "Innovation and Technology Adoption":
//       "Adopting new manufacturing technologies.",
//     "Market Expansion Capability": "Moderate, with focus on Europe.",
//     "Partnerships and Alliances": "Partnering with interior designers.",
//     "Leadership Style": "Creative and detail-oriented.",
//     "Company Culture": "Customer-focused and innovative.",
//     "Management Style": "Flexible and adaptive.",
//     "Employee Satisfaction": "High (85%)",
//     "Customer Satisfaction": "High (80%)",
//     "Stakeholder Relationships":
//       "Strong relationships with designers and suppliers.",
//     "Ethical Standards": "High ethical standards.",
//     Values: "Core values: quality, customization.",
//     "Diversity & Inclusion": "Encourages diversity and inclusion.",
//     "Transition Plan Compatibility": "Smooth transition with detailed plan.",
//     "Owner Involvement": "Owner to remain involved for 6 months.",
//     "Cultural Integration Readiness": "High readiness for integration.",
//     "Seller Story": "Founded to create bespoke furniture solutions.",
//     "Communication Style": "Direct and clear.",
//     "Decision-Making Process": "Collaborative decision-making.",
//     "Conflict Resolution": "Solution-focused.",
//     "Communication Frequency": "Frequent updates and meetings.",
//   },
//   {
//     "Business #": 3,
//     "Business Model": "Providing customized IT solutions for SMEs.",
//     "The Clients": "Tech startups and mid-sized businesses.",
//     "Value Proposition":
//       "Tailored IT solutions that boost operational efficiency.",
//     "Product/Service Offerings": 15,
//     "Revenue Streams": "Service fees, retainer contracts.",
//     "Marketing Channels": "Digital marketing, partnerships with tech hubs.",
//     "Geographic Location": "Rotterdam",
//     Revenue: 4000000,
//     "Profit Margins": "30%",
//     "Economic Indicators": "Positive, driven by tech growth.",
//     "Regulatory Environment": "Favorable for tech services.",
//     "Media Coverage": "Positive media coverage in tech sector.",
//     "Strategic Vision": "Expanding into new tech markets.",
//     "Innovation and Technology Adoption":
//       "Investing in cutting-edge technologies.",
//     "Market Expansion Capability": "High, with focus on Europe and Asia.",
//     "Partnerships and Alliances": "Partnering with tech startups.",
//     "Leadership Style": "Innovative and forward-thinking.",
//     "Company Culture": "Tech-focused and dynamic.",
//     "Management Style": "Agile and innovative.",
//     "Employee Satisfaction": "High (88%)",
//     "Customer Satisfaction": "High (90%)",
//     "Stakeholder Relationships":
//       "Strong relationships with clients and partners.",
//     "Ethical Standards": "High ethical standards.",
//     Values: "Core values: innovation, reliability.",
//     "Diversity & Inclusion": "Promotes diversity and inclusion.",
//     "Transition Plan Compatibility":
//       "Comprehensive training and transition plan.",
//     "Owner Involvement": "Owner to remain involved for 6 months.",
//     "Cultural Integration Readiness": "High readiness for integration.",
//     "Seller Story": "Founded to help SMEs with customized IT solutions.",
//     "Communication Style": "Clear and direct.",
//     "Decision-Making Process": "Collaborative, problem-solving approach.",
//     "Conflict Resolution": "Proactive and collaborative.",
//     "Communication Frequency": "Monthly strategic meetings.",
//   },
//   {
//     "Business #": 4,
//     "Business Model": "Offering specialty food products.",
//     "The Clients": "Gourmet shops and high-end restaurants.",
//     "Value Proposition":
//       "Unique specialty food products of the highest quality.",
//     "Product/Service Offerings": 40,
//     "Revenue Streams": "Product sales, direct delivery.",
//     "Marketing Channels": "Food festivals, online marketing, direct sales.",
//     "Geographic Location": "Utrecht",
//     Revenue: 2000000,
//     "Profit Margins": "35%",
//     "Economic Indicators": "Positive, driven by food trends.",
//     "Regulatory Environment": "Favorable for specialty foods.",
//     "Media Coverage": "Positive media coverage in gourmet magazines.",
//     "Strategic Vision": "Expanding product range and market presence.",
//     "Innovation and Technology Adoption": "Adopting new food technologies.",
//     "Market Expansion Capability": "Moderate, with focus on Europe.",
//     "Partnerships and Alliances": "Partnering with gourmet shops.",
//     "Leadership Style": "Creative and quality-focused.",
//     "Company Culture": "Food-focused and innovative.",
//     "Management Style": "Flexible and adaptive.",
//     "Employee Satisfaction": "High (85%)",
//     "Customer Satisfaction": "High (80%)",
//     "Stakeholder Relationships":
//       "Strong relationships with suppliers and customers.",
//     "Ethical Standards": "High ethical standards.",
//     Values: "Core values: quality, innovation.",
//     "Diversity & Inclusion": "Encourages diversity and inclusion.",
//     "Transition Plan Compatibility": "Smooth transition with detailed plan.",
//     "Owner Involvement": "Owner to remain involved for 6 months.",
//     "Cultural Integration Readiness": "High readiness for integration.",
//     "Seller Story": "Founded to offer unique specialty food products.",
//     "Communication Style": "Direct and clear.",
//     "Decision-Making Process": "Collaborative decision-making.",
//     "Conflict Resolution": "Solution-focused.",
//     "Communication Frequency": "Frequent updates and meetings.",
//   },
//   {
//     "Business #": 5,
//     "Business Model": "Providing legal services to tech startups.",
//     "The Clients": "Tech startups in need of legal support.",
//     "Value Proposition": "Comprehensive legal support for tech startups.",
//     "Product/Service Offerings": 30,
//     "Revenue Streams": "Retainer fees, hourly billing.",
//     "Marketing Channels": "Legal conferences, online marketing.",
//     "Geographic Location": "Amsterdam",
//     Revenue: 5000000,
//     "Profit Margins": "40%",
//     "Economic Indicators": "Positive, driven by tech growth.",
//     "Regulatory Environment": "Favorable for tech legal services.",
//     "Media Coverage": "Positive media coverage in tech and legal sectors.",
//     "Strategic Vision": "Expanding to more tech hubs.",
//     "Innovation and Technology Adoption":
//       "Investing in new legal technologies.",
//     "Market Expansion Capability": "Targeting international tech startups.",
//     "Partnerships and Alliances":
//       "Partnering with tech incubators and accelerators.",
//     "Leadership Style": "Innovative and client-focused.",
//     "Company Culture": "Professional and tech-savvy.",
//     "Management Style": "Agile and flexible.",
//     "Employee Satisfaction": "High (80%)",
//     "Customer Satisfaction": "High (85%)",
//     "Stakeholder Relationships": "Strong vendor and client relationships.",
//     "Ethical Standards": "Strict adherence to ethical practices.",
//     Values: "Core values: innovation, reliability.",
//     "Diversity & Inclusion": "Promotes diversity and inclusion.",
//     "Transition Plan Compatibility":
//       "Comprehensive training and transition plan.",
//     "Owner Involvement": "Owner to remain involved for 6 months.",
//     "Cultural Integration Readiness":
//       "Ready for seamless cultural integration.",
//     "Seller Story": "Established to help SMEs with customized IT solutions.",
//     "Communication Style": "Clear and direct.",
//     "Decision-Making Process": "Collaborative, problem-solving approach.",
//     "Conflict Resolution": "Proactive and collaborative.",
//     "Communication Frequency": "Monthly strategic meetings.",
//   },
// ];

// export const buyers = [
//   {
//     "Buyer #": 1,
//     "Available Capital": 3000000,
//     "Access to Financing": "High",
//     "Previous Investment Performance":
//       "Several successful exits in tech startups",
//     "Industry Experience": "10 years in tech",
//     "Strategic Vision Alignment": "Fully aligned",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities": "Highly capable",
//     "Leadership Style": "Visionary",
//     "Management Experience": "12 years in tech",
//     "Management Style": "Results-driven",
//     "Cultural Fit": "Excellent",
//     "Strategic Vision": "Expanding tech operations",
//     "Communication Style": "Clear and concise",
//     "Communication Frequency": "Regular updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Collaborative",
//     "Conflict Resolution": "Proactive",
//     "Growth Objectives": "30% annual growth",
//     "Market Expansion Plans": "Expanding to new markets",
//     "Innovation and Technology Plans": "Investing in new tech",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Strong relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story":
//       "Founded a successful tech startup, looking to diversify investments",
//   },
//   {
//     "Buyer #": 2,
//     "Available Capital": 5000000,
//     "Access to Financing": "Medium",
//     "Previous Investment Performance": "Successful healthcare investments",
//     "Industry Experience": "8 years in healthcare",
//     "Strategic Vision Alignment": "Aligned",
//     "Operational Involvement Preferences": "Prefers strategic involvement",
//     "Technological and Innovation Capabilities": "Moderate",
//     "Leadership Style": "Collaborative",
//     "Management Experience": "10 years in healthcare",
//     "Management Style": "People-oriented",
//     "Cultural Fit": "Good",
//     "Strategic Vision": "Expanding healthcare operations",
//     "Communication Style": "Clear and supportive",
//     "Communication Frequency": "Monthly updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Inclusive",
//     "Conflict Resolution": "Collaborative",
//     "Growth Objectives": "25% annual growth",
//     "Market Expansion Plans": "Expanding to new healthcare markets",
//     "Innovation and Technology Plans": "Investing in new healthcare tech",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Strong relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee satisfaction",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as consultant",
//     "Readiness for Cultural Integration": "Medium",
//     "Buyer’s Story":
//       "Experienced healthcare investor looking to expand into tech sector",
//   },
//   {
//     "Buyer #": 3,
//     "Available Capital": 7000000,
//     "Access to Financing": "High",
//     "Previous Investment Performance": "Successful finance investments",
//     "Industry Experience": "12 years in finance",
//     "Strategic Vision Alignment": "Strongly aligned",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities": "Highly capable",
//     "Leadership Style": "Visionary and strategic",
//     "Management Experience": "15 years in finance",
//     "Management Style": "Results-oriented",
//     "Cultural Fit": "Excellent",
//     "Strategic Vision": "Innovating in fintech",
//     "Communication Style": "Clear and direct",
//     "Communication Frequency": "Regular project updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Results-driven",
//     "Conflict Resolution": "Proactive",
//     "Growth Objectives": "35% annual growth",
//     "Market Expansion Plans": "Expanding to new finance markets",
//     "Innovation and Technology Plans": "Investing in fintech innovations",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Strong relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story":
//       "Successful finance investor looking to innovate in fintech",
//   },
//   {
//     "Buyer #": 4,
//     "Available Capital": 4000000,
//     "Access to Financing": "Medium",
//     "Previous Investment Performance": "Successful retail investments",
//     "Industry Experience": "10 years in retail",
//     "Strategic Vision Alignment": "Aligned",
//     "Operational Involvement Preferences": "Prefers strategic involvement",
//     "Technological and Innovation Capabilities": "Moderate",
//     "Leadership Style": "Collaborative",
//     "Management Experience": "12 years in retail",
//     "Management Style": "People-oriented",
//     "Cultural Fit": "Good",
//     "Strategic Vision": "Expanding retail operations",
//     "Communication Style": "Clear and supportive",
//     "Communication Frequency": "Monthly updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Inclusive",
//     "Conflict Resolution": "Collaborative",
//     "Growth Objectives": "25% annual growth",
//     "Market Expansion Plans": "Expanding to new retail markets",
//     "Innovation and Technology Plans": "Investing in new retail tech",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Good relationships with suppliers and customers",
//     "Employee Management and Retention Strategies":
//       "Focused on employee engagement and retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to follow existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "Medium",
//     "Buyer’s Story": "Retail investor looking to expand and innovate",
//   },
//   {
//     "Buyer #": 5,
//     "Available Capital": 6000000,
//     "Access to Financing": "High",
//     "Previous Investment Performance": "Successful tech and retail investments",
//     "Industry Experience": "15 years in tech and retail",
//     "Strategic Vision Alignment": "Strongly aligned with strategic goals",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities":
//       "Highly capable, develops innovative solutions",
//     "Leadership Style": "Visionary and results-driven",
//     "Management Experience": "18 years in tech and retail",
//     "Management Style": "Results-oriented and adaptive",
//     "Cultural Fit": "Excellent",
//     "Strategic Vision": "Expanding tech and retail operations",
//     "Communication Style": "Clear and decisive",
//     "Communication Frequency": "Frequent, project-based updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Results-driven decision making",
//     "Conflict Resolution": "Proactive and collaborative",
//     "Growth Objectives": "35% annual growth",
//     "Market Expansion Plans": "Expanding to new global markets",
//     "Innovation and Technology Plans": "Investing in new technologies",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Excellent relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee satisfaction and retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story":
//       "Experienced tech and retail investor looking to expand globally",
//   },
//   {
//     "Buyer #": 6,
//     "Available Capital": 4500000,
//     "Access to Financing": "High",
//     "Previous Investment Performance": "Successful e-commerce startup",
//     "Industry Experience": "8 years in e-commerce",
//     "Strategic Vision Alignment": "Aligned",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities": "Moderate",
//     "Leadership Style": "Visionary",
//     "Management Experience": "10 years in e-commerce",
//     "Management Style": "Results-driven",
//     "Cultural Fit": "Good",
//     "Strategic Vision": "Expanding e-commerce operations",
//     "Communication Style": "Clear and concise",
//     "Communication Frequency": "Regular updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Collaborative",
//     "Conflict Resolution": "Proactive",
//     "Growth Objectives": "30% annual growth",
//     "Market Expansion Plans": "Expanding to new markets",
//     "Innovation and Technology Plans": "Investing in new technologies",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Strong relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story":
//       "Founded a successful e-commerce startup, looking to diversify investments",
//   },
//   {
//     "Buyer #": 7,
//     "Available Capital": 5500000,
//     "Access to Financing": "High",
//     "Previous Investment Performance":
//       "Several successful exits in renewable energy",
//     "Industry Experience": "10 years in renewable energy",
//     "Strategic Vision Alignment": "Fully aligned",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities": "Highly capable",
//     "Leadership Style": "Visionary",
//     "Management Experience": "12 years in renewable energy",
//     "Management Style": "Results-driven",
//     "Cultural Fit": "Excellent",
//     "Strategic Vision": "Expanding renewable energy operations",
//     "Communication Style": "Clear and concise",
//     "Communication Frequency": "Regular updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Collaborative",
//     "Conflict Resolution": "Proactive",
//     "Growth Objectives": "30% annual growth",
//     "Market Expansion Plans": "Expanding to new markets",
//     "Innovation and Technology Plans":
//       "Investing in new renewable technologies",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Strong relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story":
//       "Experienced renewable energy investor looking to expand into tech sector",
//   },
//   {
//     "Buyer #": 8,
//     "Available Capital": 6000000,
//     "Access to Financing": "High",
//     "Previous Investment Performance": "Multiple successful exits in fintech",
//     "Industry Experience": "15 years in fintech",
//     "Strategic Vision Alignment": "Strongly aligned",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities": "Highly capable",
//     "Leadership Style": "Visionary and strategic",
//     "Management Experience": "18 years in fintech",
//     "Management Style": "Results-oriented",
//     "Cultural Fit": "Excellent",
//     "Strategic Vision": "Expanding fintech operations",
//     "Communication Style": "Clear and direct",
//     "Communication Frequency": "Frequent, project-based updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Results-driven",
//     "Conflict Resolution": "Proactive",
//     "Growth Objectives": "35% annual growth",
//     "Market Expansion Plans": "Expanding to new global markets",
//     "Innovation and Technology Plans": "Investing in fintech innovations",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Strong relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story": "Successful fintech investor looking to innovate further",
//   },
//   {
//     "Buyer #": 9,
//     "Available Capital": 7000000,
//     "Access to Financing": "High",
//     "Previous Investment Performance": "Successful exits in hospitality",
//     "Industry Experience": "12 years in hospitality",
//     "Strategic Vision Alignment": "Strongly aligned",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities": "Highly capable",
//     "Leadership Style": "Visionary and strategic",
//     "Management Experience": "15 years in hospitality",
//     "Management Style": "Results-oriented",
//     "Cultural Fit": "Excellent",
//     "Strategic Vision": "Expanding hospitality operations",
//     "Communication Style": "Clear and direct",
//     "Communication Frequency": "Frequent, project-based updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Results-driven",
//     "Conflict Resolution": "Proactive",
//     "Growth Objectives": "35% annual growth",
//     "Market Expansion Plans": "Expanding to new global markets",
//     "Innovation and Technology Plans": "Investing in hospitality innovations",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Strong relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story": "Hospitality investor looking to expand and innovate",
//   },
//   {
//     "Buyer #": 10,
//     "Available Capital": 6000000,
//     "Access to Financing": "High",
//     "Previous Investment Performance":
//       "Multiple successful exits in tech and healthcare",
//     "Industry Experience": "15 years in tech and healthcare",
//     "Strategic Vision Alignment": "Strongly aligned with strategic goals",
//     "Operational Involvement Preferences": "Prefers hands-on involvement",
//     "Technological and Innovation Capabilities":
//       "Highly capable, develops innovative solutions",
//     "Leadership Style": "Visionary and results-driven",
//     "Management Experience": "18 years in tech and healthcare",
//     "Management Style": "Results-oriented and adaptive",
//     "Cultural Fit": "Excellent",
//     "Strategic Vision": "Expanding tech and healthcare operations",
//     "Communication Style": "Clear and decisive",
//     "Communication Frequency": "Frequent, project-based updates",
//     "Ethical Standards": "High",
//     "Decision-Making Process": "Results-driven decision making",
//     "Conflict Resolution": "Proactive and collaborative",
//     "Growth Objectives": "35% annual growth",
//     "Market Expansion Plans": "Expanding to new global markets",
//     "Innovation and Technology Plans": "Investing in new technologies",
//     "Stakeholder Management Skills": "Excellent",
//     "Customer and Supplier Relationship Strategies":
//       "Excellent relationships with suppliers and clients",
//     "Employee Management and Retention Strategies":
//       "High focus on employee satisfaction and retention",
//     "Willingness to Follow Existing Transition Plans":
//       "Willing to integrate existing plans",
//     "Plans for Owner Involvement": "Plans to involve owner as advisor",
//     "Readiness for Cultural Integration": "High",
//     "Buyer’s Story":
//       "Experienced tech and healthcare investor looking to expand globally",
//   },
// ];
